repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^dev tools/
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^k8s/
      - id: check-added-large-files

  # Ruff for backend Python linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]
        types_or: [python, pyi, jupyter]
        files: ^backend/
      - id: ruff-format
        types_or: [python, pyi, jupyter]
        files: ^backend/
