name: "PR Summary & Changelog"
description: "AI-powered PR summaries to Slack/Changelog"
inputs:
  model:
    description: "AI model (gpt-3.5-turbo, gpt-4)"
    default: "gpt-3.5-turbo"
  slack_channel:
    description: "Override Slack channel"
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - shell: bash
      run: pip install openai requests
    - shell: bash
      env:
        # Embed your actual credentials here
        OPENAI_API_KEY: "sk-your-key-here"
        SLACK_WEBHOOK: "https://hooks.slack.com/your-webhook"
        CHANGELOG_WEBHOOK: "https://feedback.ionworks.com/api/changelog"
        GITHUB_TOKEN: ${{ github.token }}
        MODEL: ${{ inputs.model }}
        SLACK_CHANNEL: ${{ inputs.slack_channel }}
      run: python ${{ github.action_path }}/summarize.py
