name: "PR Summary"
description: "AI-powered PR summaries to Slack"
inputs:
  openai_api_key:
    description: "OpenAI API key"
    required: true
  slack_webhook:
    description: "Slack webhook URL"
    required: true
  model:
    description: "AI model (gpt-3.5-turbo, gpt-4)"
    default: "gpt-3.5-turbo"
  slack_channel:
    description: "Override Slack channel"
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -e ${{ github.action_path }}
    - shell: bash
      env:
        # Use inputs for secure credential storage
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        GITHUB_TOKEN: ${{ github.token }}
        MODEL: ${{ inputs.model }}
        SLACK_CHANNEL: ${{ inputs.slack_channel }}
      run: python -m pr_summary_action.summarize
