name: "PR Summary"
description: "AI-powered PR summaries to Slack"
inputs:
  model:
    description: "AI model (gpt-3.5-turbo, gpt-4)"
    default: "gpt-3.5-turbo"
  slack_channel:
    description: "Override Slack channel"
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -e ${{ github.action_path }}
    - shell: bash
      env:
        # Embed your actual credentials here
        OPENAI_API_KEY: "sk-your-key-here"
        SLACK_WEBHOOK: "https://hooks.slack.com/your-webhook"
        GITHUB_TOKEN: ${{ github.token }}
        MODEL: ${{ inputs.model }}
        SLACK_CHANNEL: ${{ inputs.slack_channel }}
      run: python -m pr_summary_action.summarize
