name: Pre-commit Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install pre-commit and Ruff
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit ruff

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
